Players now starting facing upwards ⬆️
tresinformal/game pull request #318
Opened 2021-06-01 13:42 UTC by TheoPannetier

- Fixed #298, players now start with an angle of 270 degrees (facing up, 0 = facing right)
- Adapted tests that check movement and wall collisions work as expected
- Changed wall names to the more intuitive cardinal directions 🧭. 
Note that I renamed "upper" and "lower" walls to south and north resp. "Upper" wall (y = max_y) was actually the bottom one on-screen, and "lower" wall was the top one (y = 0)

2021-06-06 12:18 UTC, TheoPannetier commented
There's more stuff now, the players coordinates are displayed in the top-right quarter of the window 👍

2021-06-09 15:44 UTC, swom requested changes
Overall very nice work, and thanks for fixing my typos.
It would if you could address my comment.

2021-06-09 15:44 UTC, ollyturner reviewed
Great Job Well Done!

2021-06-09 15:44 UTC, swom commented on game_view.cpp
> +    m_window.setView(player_coords_view);
You should make this a function `game_view::set_player_coords_view()` and maybe call it inside `draw_player_coords()`

2021-06-09 15:44 UTC, ollyturner commented
Sorry I forgot to click send

2021-06-09 15:44 UTC, merged